---
abstract: 'add a clutch to your testing drivechain'
author:
  - 'Fraser Tweedale <frase@frase.id.au>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Builder-Clutch
provides:
  Test::Builder::Clutch:
    file: lib/Test/Builder/Clutch.pm
    version: 0.05
requires:
  Class::MOP: 0
  Test::Builder: 0.98
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
